spring.application.name=persona
# Sustituye <db_password> con tu contraseña real y "tu_base_de_datos" con el nombre que quieras
spring.data.mongodb.uri=mongodb+srv://241150135_db_user:hF1loovZQwNz7BNN@itat.mjvs0cz.mongodb.net/itat?retryWrites=true&w=majority&appName=itat